[default.probe]
protocol = "Swd"
speed = 20000

[default.flashing]
enabled = false

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "RP2040"
# not supported on rp2040
connect_under_reset = false

[default.rtt]
enabled = true
up_mode = "NoBlockSkip"
channels = [
  { up = 0, down = 0, name = "name", up_mode = "NoBlockSkip", format = "Defmt" },
]
timeout = 3000
show_timestamps = true
log_enabled = false
log_path = "./logs"

[default.gdb]
enabled = false
gdb_connection_string = "127.0.0.1:2345"
